// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXM-XtxP4612UMA4zJMs1DIIDA_qpK-Q0',
    appId: '1:874365327142:web:23a5f28d1be68ec1bb93e7',
    messagingSenderId: '874365327142',
    projectId: 'wisatajawa-31ac5',
    authDomain: 'wisatajawa-31ac5.firebaseapp.com',
    storageBucket: 'wisatajawa-31ac5.firebasestorage.app',
    measurementId: 'G-Y9Z0FBTFSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6liSrFy-hGK78_FH0pVh7Z8Qgmpb8_b4',
    appId: '1:874365327142:android:25176caccddf6233bb93e7',
    messagingSenderId: '874365327142',
    projectId: 'wisatajawa-31ac5',
    storageBucket: 'wisatajawa-31ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBecW3PgFsa9IfLr4ffUDAUfz7DlzLbFTk',
    appId: '1:874365327142:ios:3790c15c3d432c09bb93e7',
    messagingSenderId: '874365327142',
    projectId: 'wisatajawa-31ac5',
    storageBucket: 'wisatajawa-31ac5.firebasestorage.app',
    iosBundleId: 'com.example.wisataJawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBecW3PgFsa9IfLr4ffUDAUfz7DlzLbFTk',
    appId: '1:874365327142:ios:3790c15c3d432c09bb93e7',
    messagingSenderId: '874365327142',
    projectId: 'wisatajawa-31ac5',
    storageBucket: 'wisatajawa-31ac5.firebasestorage.app',
    iosBundleId: 'com.example.wisataJawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXM-XtxP4612UMA4zJMs1DIIDA_qpK-Q0',
    appId: '1:874365327142:web:28a4498c7c6dd12cbb93e7',
    messagingSenderId: '874365327142',
    projectId: 'wisatajawa-31ac5',
    authDomain: 'wisatajawa-31ac5.firebaseapp.com',
    storageBucket: 'wisatajawa-31ac5.firebasestorage.app',
    measurementId: 'G-6TS743GCDR',
  );
}
